module.exports = {
  LOAD_TASKS_REQUEST: "task/LOAD_TASKS_REQUEST",
  LOAD_TASKS_ERROR: "task/LOAD_TASKS_ERROR",
  LOAD_TASKS_SUCCESS: "task/LOAD_TASKS_SUCCESS",
  ADD_NEW_TASK_REQUEST: "task/ADD_NEW_TASK_REQUEST",
  ADD_NEW_TASK_ERROR: "task/ADD_NEW_TASK_ERROR",
  ADD_NEW_TASK_SUCCESS: "task/ADD_NEW_TASK_SUCCESS",
  COMPLETE_TASK_REQUEST: "task/COMPLETE_TASK_REQUEST",
  COMPLETE_TASK_ERROR: "task/COMPLETE_TASK_ERROR",
  COMPLETE_TASK_SUCCESS: "task/COMPLETE_TASK_SUCCESS",
};